---
name: GKE-Dev_UI
on:
  workflow_dispatch: null
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_LOGIN_SERVER }}  
          
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER2_NAME }}
          location: ${{ secrets.GKE_LOCATION }}
          project_id: ${{ secrets.GKE_PROJECT }}
          
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
           
      - name: Build and push Docker container
        run: |
          IMAGE=us-central1-docker.pkg.dev/konaai-dev-462909/konaai-gke/dev-ui
          docker build -f OrgKonaAI/Dockerfile -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}

          # Optional: also push "latest" tag
          docker tag $IMAGE:${{ github.sha }} $IMAGE:latest
          docker push $IMAGE:latest

      - name: Ensure ingress-nginx is installed
        run: |
          if helm status ingress-nginx -n ingress-nginx >/dev/null 2>&1; then
           echo "Ingress-NGINX already installed, skipping..."
          else
           echo "Installing Ingress-NGINX..."
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
            helm repo update
            helm install ingress-nginx ingress-nginx/ingress-nginx \
             --create-namespace \
             --namespace ingress-nginx
           fi
           echo " Checking if TLS secret 'godaddy-wildcard' exists in namespace 'ingress-nginx'..."
           if kubectl get secret godaddy-wildcard -n ingress-nginx >/dev/null 2>&1; then
             echo "TLS secret 'godaddy-wildcard' already exists. Skipping creation."
           else
            echo " Creating TLS secret 'godaddy-wildcard'..."
            echo "${{ secrets.TLS_FULLCHAIN_CRT }}" > /tmp/fullchain.crt
            echo "${{ secrets.TLS_PRIVATE_KEY }}" > /tmp/private.key
            
            kubectl create secret tls godaddy-wildcard \
              --cert=/tmp/fullchain.crt \
              --key=/tmp/private.key \
              -n ingress-nginx
            echo "TLS secret 'godaddy-wildcard' created successfully in namespace 'ingress-nginx'."
          fi
      - name: Helm install or upgrade
        run: |
         RELEASE_NAME=ui-app
         NAMESPACE=konaai-dev-ui
         CHART_PATH=./OrgKonaAI/GKE-charts  # ✅ path where Chart.yaml exists

           # Make sure namespace exists (avoids "not found" errors)
         kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE

         # Run Helm upgrade/install
         helm upgrade --install $RELEASE_NAME $CHART_PATH \
         --namespace $NAMESPACE \
         --values ./OrgKonaAI/GKE-charts/values-dev.yaml \
         --wait \
         --atomic \
         --timeout 3m


           
